# Project information
site_name: Angela Bartz
site_author: Angela Bartz
site_url: https://abartzgit.github.io/angelabartz/

# Copyright
copyright: Copyright &copy; 2026 Angela Bartz

# Add extensions for Markdown processing, including support for attributes, Markdown in HTML, and admonitions.
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      toc_depth: 2

# Configuration
theme: 
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  # Auto-expand the left navigation and include previous and next navigation in the footer.
  features: 
    - navigation.footer
  
  # Set the color palette for light and dark mode, and include a toggle to switch between them.
  palette:
    
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

# Extras
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/1125538089457160232
    - icon: fontawesome/brands/github
      link: https://github.com/ABartzGit/angelabartz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angela-bartz/

extra_css:
  - stylesheets/extra.css

# Site navigation
nav: 
  - Home: index.md
  - Portfolio: my-portfolio.md
  - Blog: blog.md
  - My writing journey: my-writing-journey.md
  - Archived:
    - Riley's blog: blog-archived/riley-blog.md
