# Project information
site_name: Angela Bartz
site_author: Angela Bartz
site_url: https://abartzgit.github.io/angelabartz/

# Copyright
copyright: Copyright &copy; 2026 Angela Bartz

# Add extensions for Markdown processing, including support for attributes, Markdown in HTML, and admonitions.
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition

# Configuration
theme: 
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  # Auto-expand the left navigation and include previous and next navigation in the footer.
  features: 
    - navigation.expand
    - navigation.footer
  
  # Set the color palette for light and dark mode, and include a toggle to switch between them.
  palette:
    
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

# Extras
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/1125538089457160232
    - icon: fontawesome/brands/github
      link: https://github.com/ABartzGit/angelabartz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angela-bartz/

# Site navigation
nav: 
  - About me: index.md
  - My writing journey: my-writing-journey.md
  - Technical writing portfolio: my-portfolio.md
  - Blog:
    - June 8, 2026 Tech writing managers -- value beyond documentation: blog/tw-manager-value.md
    - July 2, 2026 Creating open-source site with MkDocs: blog/mkdocs-site.md
  - Archived:
    - Riley's blog: blog-archived/riley-blog.md
